services:
  - type: web
    name: lawyers-management-system
    env: node
    runtime: node
    buildCommand: npm ci --ignore-scripts && npm run postinstall && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
        generateValue: true
      - key: NEXTAUTH_SECRET
        sync: false
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
